# Generated by Django 3.0.6 on 2021-07-23 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_moneda', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField(auto_now_add=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('usuario', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Cliente')),
                ('id_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Cuenta')),
                ('id_tipo_moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Tipo_Moneda')),
                ('id_tipo_transaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Tipo_Transaccion')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_CCDev.Tipo_Cuenta'),
        ),
    ]
