# Generated by Django 3.0.6 on 2021-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CCDev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNT_BANK',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DATES', models.CharField(max_length=8)),
                ('DESCR', models.CharField(max_length=500)),
                ('ID_CLIENT', models.CharField(max_length=100)),
                ('TYPE', models.CharField(max_length=1)),
                ('DEBT', models.FloatField()),
                ('CRED', models.FloatField()),
                ('BALANCE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=250)),
                ('ORIGIN', models.CharField(max_length=30)),
                ('AGE', models.PositiveIntegerField()),
                ('STATUS', models.CharField(max_length=10)),
            ],
        ),
    ]
